postgres:
  host: 127.0.0.1
  port: 5432
  database: hive_metastore
  
  #TODO: Should be able to provide username and password from a secret instead of raw values
  username:
    rawValue: postgres
  password:
    rawValue: postgres

autoCreateSchema: false
warehouseDir: file:///tmp 

blobStorages:
  
  s3aConfiguration:
    accessKeyId: 
    secretAccessKey: 
    endpoint: 
    pathStyleAccess: true
    sslEnabled: false
    s3aWarehousePath: s3a://test


hiveConfigParameters:
  - key: hive.metastore.uris
    value: trift://0.0.0.0:9083

image:
  repository: xujavy/hive
  tag: v0.0.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  hive/service: hive-metastore

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9083

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
